# Generated by Django 6.0 on 2025-12-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wishlist_servicerequest_servicequeue_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_general',
            field=models.BooleanField(default=True, verbose_name='Genel Bildirimler'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_price_drops',
            field=models.BooleanField(default=True, verbose_name='Fiyat Düşüşleri'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_recommendations',
            field=models.BooleanField(default=True, verbose_name='Ürün Önerileri'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_restock',
            field=models.BooleanField(default=True, verbose_name='Stok Bildirimleri'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_service_updates',
            field=models.BooleanField(default=True, verbose_name='Servis Güncellemeleri'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_warranty_expiry',
            field=models.BooleanField(default=True, verbose_name='Garanti Süresi Uyarıları'),
        ),
    ]
