# Generated by Django 4.2.7 on 2026-01-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_notification_notif_user_read_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='İlçe Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='open_address',
            field=models.TextField(blank=True, help_text='Ev/Apartman numarası, cadde, sokak vb.', null=True, verbose_name='Açık Adres'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahalle/Köy Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='products.district', verbose_name='İlçe')),
            ],
            options={
                'verbose_name': 'Mahalle/Köy',
                'verbose_name_plural': 'Mahalle/Köyler',
                'ordering': ['district__name', 'name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='products.area', verbose_name='Mahalle/Köy'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='products.district', verbose_name='İlçe'),
        ),
    ]
