# Generated by Django 4.2.7 on 2026-01-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productassignment_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Merkez Enlem'),
        ),
        migrations.AddField(
            model_name='district',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Merkez Boylam'),
        ),
    ]
