# Generated by Django 4.2.7 on 2026-01-08 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_district_center_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Lefkoşa Ana Depo, Gazimağusa Şube', max_length=100, unique=True, verbose_name='Depo Adı')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Boylam')),
                ('is_default', models.BooleanField(default=False, help_text='Yalnızca bir depo varsayılan olabilir', verbose_name='Varsayılan Depo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depots', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Depo Konumu',
                'verbose_name_plural': 'Depo Konumları',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='products.depotlocation', verbose_name='Başlangıç Deposu'),
        ),
    ]
